name: IslandTPAfk
version: ${project.version}
main: net.lapismc.afkplus.AFKPlus
api-version: 1.21
folia-supported: true
softdepend: [ PlaceholderAPI, Essentials, LuckPerms, DiscordSRV ]
authors: [WarnD]
description: AFK for professional servers
